### ISSUE TITLE
Remove unused files

### ISSUE THREAD

**Issue by hkiyomaru** [ku-nlp/ja-vicuna-qa-benchmark#6]
## Why

Currently, there are several unused files in the repository, making it difficult to navigate and maintain.

## How

Identify and remove all unused files. I recommend removing backup files like `gen_model_answer_ori.py`. Since this project is tracked with Git, the files can be restored if needed in the future.

**Comment by hkiyomaru** [comment]
There are still some files that remain unused, like `llm_judge/moduiles/gptq.py`. While they cannot be indiscriminately deleted because they are imported by other sections of the code, they are essentially not needed.

**Comment by YukinoWan** [comment]
Ok, I will continue removing
