### ISSUE TITLE
Rename the repository

### ISSUE THREAD

**Issue by hkiyomaru** [ku-nlp/ja-vicuna-qa-benchmark#9]
### Why

The current repository name, `LLM_Judge_ku`,  doesn't adequately reflect the project's focus and scope. Besides, the capitalization is not consistent.

### How

To improve clarity and maintain consistency in naming conventions, I suggest renaming the repository to `ja-vicuna-qa-benchmark` or a similar alternative.

### Additional Consideration

Given that this project has evolved beyond a personal initiative, it would be appropriate to transfer the repository to the [ku-nlp](https://github.com/ku-nlp) organization.

### Note

Upon renaming and relocating the repository, GitHub will automatically redirect requests from the old URL to the new one.

**Comment by hitoshizuku7** [comment]
Looks like it's done.
